services:
  frontend:
    image: shopco_frontend
    build:
      context: ./client
    ports:
      - "80:80"
    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 5000
    depends_on:
      - backend

  backend:
    image: shopco_backend
    build:
      context: ./server
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: shop_co
      DB_USER: postgres
      DB_PASSWORD: postgrespoi

  db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: shop_co
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespoi
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
